apiVersion: batch/v1
kind: CronJob
metadata:
  name: lkjlkj
spec:
  jobTemplate:
    metadata:
      name: lkjlkjlk
      labels:
        app: welkjlkj
    spec:
      template:
        spec:
          volumes:
            - name: lkjlk,lkjlkj,lkjlkj
              hostPath:
                path: /lkjkl/lkjlkjlkj
          containers:
            - name: mlkjlkj
              image: mysql:latest
              ports:
                - containerPort: 80
              volumeMounts:
                - mountPath: /lkjlkj/lkjlkj
                  name: lkjlk,lkjlkj,lkjlkj
          restartPolicy: Never
  schedule: "kljlkj"
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbod

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lkjlkj
  labels:
    app: lkjlkj
spec:
  selector:
    matchLabels:
      app: lkjlkj
    matchExpressions:
      - key: lkjlkj
        operator: Exists
  template:
    metadata:
      name: lkjlkj
      labels:
        app: lkjdslkj
    spec:
      volumes:
        - name: lkjkl,lkjlkji,kjlkjl
          hostPath:
            path: /lkjkl/lkjlkj
            type: Directory
      containers:
        - name: lkjljk
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /lkjlkj/lkjlkj
              name: lkjkl,lkjlkji,kjlkjl

































































































